//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GestionProcesosConocer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class k_Persona
    {
        public long FL_PERSONA { get; set; }
        public string NB_PERSONA { get; set; }
        public string NB_APELLIDO_PATERNO { get; set; }
        public string NB_APELLIDO_MATERNO { get; set; }
        public Nullable<System.DateTime> FE_NACIMIENTO { get; set; }
        public string DS_CURP { get; set; }
        public string DS_CORREO { get; set; }
        public Nullable<bool> FG_ACTIVO { get; set; }
    }
}
